// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Stetic {
    
    
    internal class Gui {
        
        public static void Build(object obj, System.Type type) {
            Stetic.Gui.Build(obj, type.FullName);
        }
        
        public static void Build(object obj, string id) {
            System.Collections.Hashtable bindings = new System.Collections.Hashtable();
            if ((id == "MainWindow")) {
                Gtk.Window cobj = ((Gtk.Window)(obj));
                // Widget MainWindow
                cobj.Title = "NDStation Patcher";
                Gtk.UIManager w1 = new Gtk.UIManager();
                Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
                w1.InsertActionGroup(w2, 0);
                cobj.AddAccelGroup(w1.AccelGroup);
                cobj.Icon = Gtk.IconTheme.Default.LoadIcon("stock_score-normal", 16, 0);
                cobj.WindowPosition = ((Gtk.WindowPosition)(4));
                cobj.DefaultWidth = 1;
                cobj.Events = ((Gdk.EventMask)(0));
                cobj.Name = "MainWindow";
                // Container child MainWindow.Gtk.Container+ContainerChild
                Gtk.VBox w3 = new Gtk.VBox();
                w3.Events = ((Gdk.EventMask)(0));
                w3.Name = "vbox1";
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.VBox w4 = new Gtk.VBox();
                w4.Events = ((Gdk.EventMask)(0));
                w4.Name = "vbox3";
                // Container child vbox3.Gtk.Box+BoxChild
                Gtk.Image w5 = new Gtk.Image();
                w5.Pixbuf = Gdk.Pixbuf.LoadFromResource("top.bmp");
                w5.Events = ((Gdk.EventMask)(0));
                w5.Name = "image2";
                bindings["image2"] = w5;
                w4.Add(w5);
                Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(w4[w5]));
                w6.Position = 0;
                w6.Expand = false;
                w6.Fill = false;
                // Container child vbox3.Gtk.Box+BoxChild
                Gtk.HBox w7 = new Gtk.HBox();
                w7.Events = ((Gdk.EventMask)(0));
                w7.Name = "hbox1";
                // Container child hbox1.Gtk.Box+BoxChild
                Gtk.Label w8 = new Gtk.Label();
                w8.LabelProp = "GBA ROM File:  ";
                w8.Justify = ((Gtk.Justification)(2));
                w8.Events = ((Gdk.EventMask)(0));
                w8.Name = "label2";
                bindings["label2"] = w8;
                w7.Add(w8);
                Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w7[w8]));
                w9.Position = 0;
                w9.Expand = false;
                w9.Fill = false;
                // Container child hbox1.Gtk.Box+BoxChild
                Gtk.Entry w10 = new Gtk.Entry();
                w10.IsEditable = true;
                w10.InvisibleChar = '●';
                w10.CanFocus = true;
                w10.Events = ((Gdk.EventMask)(0));
                w10.Name = "entry2";
                bindings["entry2"] = w10;
                w7.Add(w10);
                Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(w7[w10]));
                w11.Position = 1;
                // Container child hbox1.Gtk.Box+BoxChild
                Gtk.Button w12 = new Gtk.Button();
                w12.UseUnderline = true;
                w12.CanFocus = true;
                w12.Events = ((Gdk.EventMask)(0));
                w12.Name = "button10";
                w12.Label = "Browse...";
                bindings["button10"] = w12;
                w7.Add(w12);
                Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(w7[w12]));
                w13.Position = 2;
                w13.Expand = false;
                w13.Fill = false;
                bindings["hbox1"] = w7;
                w4.Add(w7);
                Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(w4[w7]));
                w14.Position = 1;
                w14.Expand = false;
                w14.Fill = false;
                // Container child vbox3.Gtk.Box+BoxChild
                Gtk.VBox w15 = new Gtk.VBox();
                w15.Events = ((Gdk.EventMask)(0));
                w15.Name = "vbox4";
                // Container child vbox4.Gtk.Box+BoxChild
                Gtk.Label w16 = new Gtk.Label();
                w16.LabelProp = "Put a GBA File here.";
                w16.Xalign = 0.24F;
                w16.Events = ((Gdk.EventMask)(0));
                w16.Name = "label3";
                bindings["label3"] = w16;
                w15.Add(w16);
                Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(w15[w16]));
                w17.Position = 0;
                w17.Expand = false;
                w17.Fill = false;
                // Container child vbox4.Gtk.Box+BoxChild
                Gtk.HBox w18 = new Gtk.HBox();
                w18.Events = ((Gdk.EventMask)(0));
                w18.Name = "hbox2";
                // Container child hbox2.Gtk.Box+BoxChild
                Gtk.Label w19 = new Gtk.Label();
                w19.LabelProp = "Output File:     ";
                w19.Xpad = 1;
                w19.Events = ((Gdk.EventMask)(0));
                w19.Name = "label1";
                bindings["label1"] = w19;
                w18.Add(w19);
                Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(w18[w19]));
                w20.Position = 0;
                w20.Expand = false;
                w20.Fill = false;
                // Container child hbox2.Gtk.Box+BoxChild
                Gtk.Entry w21 = new Gtk.Entry();
                w21.IsEditable = true;
                w21.InvisibleChar = '●';
                w21.CanFocus = true;
                w21.Events = ((Gdk.EventMask)(0));
                w21.Name = "entry1";
                bindings["entry1"] = w21;
                w18.Add(w21);
                Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(w18[w21]));
                w22.Position = 1;
                w22.Padding = ((uint)(3));
                // Container child hbox2.Gtk.Box+BoxChild
                Gtk.Button w23 = new Gtk.Button();
                w23.CanFocus = true;
                w23.Events = ((Gdk.EventMask)(0));
                w23.Name = "button3";
                w23.Label = "Browse...";
                bindings["button3"] = w23;
                w18.Add(w23);
                Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(w18[w23]));
                w24.Position = 2;
                w24.Expand = false;
                w24.Fill = false;
                bindings["hbox2"] = w18;
                w15.Add(w18);
                Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(w15[w18]));
                w25.Position = 1;
                w25.Expand = false;
                w25.Fill = false;
                // Container child vbox4.Gtk.Box+BoxChild
                Gtk.VBox w26 = new Gtk.VBox();
                w26.Events = ((Gdk.EventMask)(0));
                w26.Name = "vbox5";
                // Container child vbox5.Gtk.Box+BoxChild
                Gtk.HBox w27 = new Gtk.HBox();
                w27.Events = ((Gdk.EventMask)(0));
                w27.Name = "hbox3";
                // Container child hbox3.Gtk.Box+BoxChild
                Gtk.DrawingArea w28 = new Gtk.DrawingArea();
                w28.Events = ((Gdk.EventMask)(0));
                w28.Name = "drawingarea1";
                bindings["drawingarea1"] = w28;
                w27.Add(w28);
                Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(w27[w28]));
                w29.Position = 0;
                bindings["hbox3"] = w27;
                w26.Add(w27);
                Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(w26[w27]));
                w30.Position = 0;
                // Container child vbox5.Gtk.Box+BoxChild
                Gtk.HBox w31 = new Gtk.HBox();
                w31.Events = ((Gdk.EventMask)(0));
                w31.Name = "hbox4";
                // Container child hbox4.Gtk.Box+BoxChild
                Gtk.Label w32 = new Gtk.Label();
                w32.LabelProp = "Game Title:      ";
                w32.Xpad = 1;
                w32.Events = ((Gdk.EventMask)(0));
                w32.Name = "label4";
                bindings["label4"] = w32;
                w31.Add(w32);
                Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(w31[w32]));
                w33.Position = 0;
                w33.Expand = false;
                w33.Fill = false;
                // Container child hbox4.Gtk.Box+BoxChild
                Gtk.Entry w34 = new Gtk.Entry();
                w34.IsEditable = true;
                w34.InvisibleChar = '●';
                w34.CanFocus = true;
                w34.Events = ((Gdk.EventMask)(0));
                w34.Name = "entry3";
                bindings["entry3"] = w34;
                w31.Add(w34);
                Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(w31[w34]));
                w35.Position = 1;
                bindings["hbox4"] = w31;
                w26.Add(w31);
                Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(w26[w31]));
                w36.Position = 1;
                w36.Expand = false;
                w36.Fill = false;
                // Container child vbox5.Gtk.Box+BoxChild
                Gtk.HBox w37 = new Gtk.HBox();
                w37.Events = ((Gdk.EventMask)(0));
                w37.Name = "hbox5";
                // Container child hbox5.Gtk.Box+BoxChild
                Gtk.Label w38 = new Gtk.Label();
                w38.LabelProp = "";
                w38.Justify = ((Gtk.Justification)(1));
                w38.Xpad = 49;
                w38.Events = ((Gdk.EventMask)(0));
                w38.Name = "label5";
                bindings["label5"] = w38;
                w37.Add(w38);
                Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(w37[w38]));
                w39.Position = 0;
                w39.Expand = false;
                w39.Fill = false;
                // Container child hbox5.Gtk.Box+BoxChild
                Gtk.Entry w40 = new Gtk.Entry();
                w40.IsEditable = true;
                w40.InvisibleChar = '●';
                w40.CanFocus = true;
                w40.Events = ((Gdk.EventMask)(0));
                w40.Name = "entry4";
                bindings["entry4"] = w40;
                w37.Add(w40);
                Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(w37[w40]));
                w41.Position = 1;
                w41.Padding = ((uint)(1));
                bindings["hbox5"] = w37;
                w26.Add(w37);
                Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(w26[w37]));
                w42.Position = 2;
                w42.Expand = false;
                w42.Fill = false;
                bindings["vbox5"] = w26;
                w15.Add(w26);
                Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(w15[w26]));
                w43.Position = 2;
                bindings["vbox4"] = w15;
                w4.Add(w15);
                Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(w4[w15]));
                w44.Position = 2;
                bindings["vbox3"] = w4;
                w3.Add(w4);
                Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(w3[w4]));
                w45.Position = 0;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.VBox w46 = new Gtk.VBox();
                w46.Events = ((Gdk.EventMask)(0));
                w46.Name = "vbox6";
                // Container child vbox6.Gtk.Box+BoxChild
                Gtk.HBox w47 = new Gtk.HBox();
                w47.Events = ((Gdk.EventMask)(0));
                w47.Name = "hbox6";
                // Container child hbox6.Gtk.Box+BoxChild
                Gtk.Label w48 = new Gtk.Label();
                w48.LabelProp = "";
                w48.Xpad = 49;
                w48.Events = ((Gdk.EventMask)(0));
                w48.Name = "label6";
                bindings["label6"] = w48;
                w47.Add(w48);
                Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(w47[w48]));
                w49.Position = 0;
                w49.Expand = false;
                w49.Fill = false;
                // Container child hbox6.Gtk.Box+BoxChild
                Gtk.Entry w50 = new Gtk.Entry();
                w50.IsEditable = true;
                w50.InvisibleChar = '●';
                w50.CanFocus = true;
                w50.Events = ((Gdk.EventMask)(0));
                w50.Name = "entry5";
                bindings["entry5"] = w50;
                w47.Add(w50);
                Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(w47[w50]));
                w51.Position = 1;
                w51.Padding = ((uint)(1));
                bindings["hbox6"] = w47;
                w46.Add(w47);
                Gtk.Box.BoxChild w52 = ((Gtk.Box.BoxChild)(w46[w47]));
                w52.Position = 0;
                w52.Expand = false;
                w52.Fill = false;
                // Container child vbox6.Gtk.Box+BoxChild
                Gtk.VBox w53 = new Gtk.VBox();
                w53.Events = ((Gdk.EventMask)(0));
                w53.Name = "vbox9";
                // Container child vbox9.Gtk.Box+BoxChild
                Gtk.HBox w54 = new Gtk.HBox();
                w54.Events = ((Gdk.EventMask)(0));
                w54.Name = "hbox7";
                // Container child hbox7.Gtk.Box+BoxChild
                Gtk.HBox w55 = new Gtk.HBox();
                w55.Events = ((Gdk.EventMask)(0));
                w55.Name = "hbox8";
                // Container child hbox8.Gtk.Box+BoxChild
                Gtk.CheckButton w56 = new Gtk.CheckButton();
                w56.Label = "Use PSRAM";
                w56.DrawIndicator = true;
                w56.CanFocus = true;
                w56.Events = ((Gdk.EventMask)(0));
                w56.Name = "checkbutton1";
                bindings["checkbutton1"] = w56;
                w55.Add(w56);
                Gtk.Box.BoxChild w57 = ((Gtk.Box.BoxChild)(w55[w56]));
                w57.Position = 0;
                bindings["hbox8"] = w55;
                w54.Add(w55);
                Gtk.Box.BoxChild w58 = ((Gtk.Box.BoxChild)(w54[w55]));
                w58.Position = 0;
                // Container child hbox7.Gtk.Box+BoxChild
                Gtk.CheckButton w59 = new Gtk.CheckButton();
                w59.Label = "Save the Whales";
                w59.Active = true;
                w59.DrawIndicator = true;
                w59.CanFocus = true;
                w59.Events = ((Gdk.EventMask)(0));
                w59.Name = "checkbutton2";
                bindings["checkbutton2"] = w59;
                w54.Add(w59);
                Gtk.Box.BoxChild w60 = ((Gtk.Box.BoxChild)(w54[w59]));
                w60.Position = 1;
                bindings["hbox7"] = w54;
                w53.Add(w54);
                Gtk.Box.BoxChild w61 = ((Gtk.Box.BoxChild)(w53[w54]));
                w61.Position = 0;
                w61.Expand = false;
                w61.Fill = false;
                bindings["vbox9"] = w53;
                w46.Add(w53);
                Gtk.Box.BoxChild w62 = ((Gtk.Box.BoxChild)(w46[w53]));
                w62.Position = 1;
                w62.Expand = false;
                w62.Fill = false;
                // Container child vbox6.Gtk.Box+BoxChild
                Gtk.VBox w63 = new Gtk.VBox();
                w63.Events = ((Gdk.EventMask)(0));
                w63.Name = "vbox8";
                // Container child vbox8.Gtk.Box+BoxChild
                Gtk.VBox w64 = new Gtk.VBox();
                w64.Events = ((Gdk.EventMask)(0));
                w64.Name = "vbox10";
                // Container child vbox10.Gtk.Box+BoxChild
                Gtk.DrawingArea w65 = new Gtk.DrawingArea();
                w65.Events = ((Gdk.EventMask)(0));
                w65.Name = "drawingarea6";
                bindings["drawingarea6"] = w65;
                w64.Add(w65);
                Gtk.Box.BoxChild w66 = ((Gtk.Box.BoxChild)(w64[w65]));
                w66.Position = 0;
                // Container child vbox10.Gtk.Box+BoxChild
                Gtk.Label w67 = new Gtk.Label();
                w67.LabelProp = "<u>Customize NDS...</u>";
                w67.UseMarkup = true;
                w67.UseUnderline = true;
                w67.Events = ((Gdk.EventMask)(0));
                w67.Name = "label8";
                bindings["label8"] = w67;
                w64.Add(w67);
                Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(w64[w67]));
                w68.Position = 1;
                w68.Expand = false;
                w68.Fill = false;
                // Container child vbox10.Gtk.Box+BoxChild
                Gtk.HBox w69 = new Gtk.HBox();
                w69.Events = ((Gdk.EventMask)(0));
                w69.Name = "hbox9";
                // Container child hbox9.Gtk.Box+BoxChild
                Gtk.HBox w70 = new Gtk.HBox();
                w70.Events = ((Gdk.EventMask)(0));
                w70.Name = "hbox11";
                // Container child hbox11.Gtk.Box+BoxChild
                Gtk.Label w71 = new Gtk.Label();
                w71.LabelProp = "Custom Icon:     ";
                w71.Events = ((Gdk.EventMask)(0));
                w71.Name = "label9";
                bindings["label9"] = w71;
                w70.Add(w71);
                Gtk.Box.BoxChild w72 = ((Gtk.Box.BoxChild)(w70[w71]));
                w72.Position = 0;
                w72.Expand = false;
                w72.Fill = false;
                // Container child hbox11.Gtk.Box+BoxChild
                Gtk.Entry w73 = new Gtk.Entry();
                w73.IsEditable = true;
                w73.InvisibleChar = '●';
                w73.CanFocus = true;
                w73.Events = ((Gdk.EventMask)(0));
                w73.Name = "entry6";
                bindings["entry6"] = w73;
                w70.Add(w73);
                Gtk.Box.BoxChild w74 = ((Gtk.Box.BoxChild)(w70[w73]));
                w74.Position = 1;
                // Container child hbox11.Gtk.Box+BoxChild
                Gtk.Button w75 = new Gtk.Button();
                w75.CanFocus = true;
                w75.Events = ((Gdk.EventMask)(0));
                w75.Name = "button12";
                w75.Label = "Browse...";
                bindings["button12"] = w75;
                w70.Add(w75);
                Gtk.Box.BoxChild w76 = ((Gtk.Box.BoxChild)(w70[w75]));
                w76.Position = 2;
                w76.Expand = false;
                w76.Fill = false;
                bindings["hbox11"] = w70;
                w69.Add(w70);
                Gtk.Box.BoxChild w77 = ((Gtk.Box.BoxChild)(w69[w70]));
                w77.Position = 0;
                bindings["hbox9"] = w69;
                w64.Add(w69);
                Gtk.Box.BoxChild w78 = ((Gtk.Box.BoxChild)(w64[w69]));
                w78.Position = 2;
                w78.Expand = false;
                w78.Fill = false;
                bindings["vbox10"] = w64;
                w63.Add(w64);
                Gtk.Box.BoxChild w79 = ((Gtk.Box.BoxChild)(w63[w64]));
                w79.Position = 0;
                bindings["vbox8"] = w63;
                w46.Add(w63);
                Gtk.Box.BoxChild w80 = ((Gtk.Box.BoxChild)(w46[w63]));
                w80.Position = 2;
                bindings["vbox6"] = w46;
                w3.Add(w46);
                Gtk.Box.BoxChild w81 = ((Gtk.Box.BoxChild)(w3[w46]));
                w81.Position = 1;
                // Container child vbox1.Gtk.Box+BoxChild
                Gtk.VBox w82 = new Gtk.VBox();
                w82.Events = ((Gdk.EventMask)(0));
                w82.Name = "vbox2";
                // Container child vbox2.Gtk.Box+BoxChild
                Gtk.VBox w83 = new Gtk.VBox();
                w83.Events = ((Gdk.EventMask)(0));
                w83.Name = "vbox7";
                // Container child vbox7.Gtk.Box+BoxChild
                Gtk.VBox w84 = new Gtk.VBox();
                w84.Events = ((Gdk.EventMask)(0));
                w84.Name = "vbox11";
                // Container child vbox11.Gtk.Box+BoxChild
                Gtk.Label w85 = new Gtk.Label();
                w85.LabelProp = "32x32 - 4-bit color (.bmp)";
                w85.Events = ((Gdk.EventMask)(0));
                w85.Name = "label11";
                bindings["label11"] = w85;
                w84.Add(w85);
                Gtk.Box.BoxChild w86 = ((Gtk.Box.BoxChild)(w84[w85]));
                w86.Position = 0;
                w86.Expand = false;
                w86.Fill = false;
                bindings["vbox11"] = w84;
                w83.Add(w84);
                Gtk.Box.BoxChild w87 = ((Gtk.Box.BoxChild)(w83[w84]));
                w87.Position = 0;
                w87.Expand = false;
                w87.Fill = false;
                // Container child vbox7.Gtk.Box+BoxChild
                Gtk.HBox w88 = new Gtk.HBox();
                w88.Events = ((Gdk.EventMask)(0));
                w88.Name = "hbox10";
                // Container child hbox10.Gtk.Box+BoxChild
                Gtk.Label w89 = new Gtk.Label();
                w89.LabelProp = "<s>Custom Border: </s>";
                w89.UseMarkup = true;
                w89.Events = ((Gdk.EventMask)(0));
                w89.Name = "label10";
                bindings["label10"] = w89;
                w88.Add(w89);
                Gtk.Box.BoxChild w90 = ((Gtk.Box.BoxChild)(w88[w89]));
                w90.Position = 0;
                w90.Expand = false;
                w90.Fill = false;
                // Container child hbox10.Gtk.Box+BoxChild
                Gtk.Entry w91 = new Gtk.Entry();
                w91.IsEditable = false;
                w91.InvisibleChar = '●';
                w91.CanFocus = true;
                w91.Events = ((Gdk.EventMask)(0));
                w91.Name = "entry10";
                bindings["entry10"] = w91;
                w88.Add(w91);
                Gtk.Box.BoxChild w92 = ((Gtk.Box.BoxChild)(w88[w91]));
                w92.Position = 1;
                // Container child hbox10.Gtk.Box+BoxChild
                Gtk.Button w93 = new Gtk.Button();
                w93.CanFocus = true;
                w93.Events = ((Gdk.EventMask)(0));
                w93.Name = "button13";
                w93.Label = "Browse...";
                bindings["button13"] = w93;
                w88.Add(w93);
                Gtk.Box.BoxChild w94 = ((Gtk.Box.BoxChild)(w88[w93]));
                w94.Position = 2;
                w94.Expand = false;
                w94.Fill = false;
                bindings["hbox10"] = w88;
                w83.Add(w88);
                Gtk.Box.BoxChild w95 = ((Gtk.Box.BoxChild)(w83[w88]));
                w95.Position = 1;
                w95.Expand = false;
                w95.Fill = false;
                // Container child vbox7.Gtk.Box+BoxChild
                Gtk.Label w96 = new Gtk.Label();
                w96.LabelProp = "<s>256x192, 24-bit color</s> (currently unsupported)";
                w96.UseMarkup = true;
                w96.Events = ((Gdk.EventMask)(0));
                w96.Name = "label12";
                bindings["label12"] = w96;
                w83.Add(w96);
                Gtk.Box.BoxChild w97 = ((Gtk.Box.BoxChild)(w83[w96]));
                w97.Position = 2;
                w97.Expand = false;
                w97.Fill = false;
                bindings["vbox7"] = w83;
                w82.Add(w83);
                Gtk.Box.BoxChild w98 = ((Gtk.Box.BoxChild)(w82[w83]));
                w98.Position = 0;
                w98.Expand = false;
                w98.Fill = false;
                // Container child vbox2.Gtk.Box+BoxChild
                Gtk.HButtonBox w99 = new Gtk.HButtonBox();
                w99.Events = ((Gdk.EventMask)(0));
                w99.Name = "hbuttonbox2";
                // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
                Gtk.Button w100 = new Gtk.Button();
                w100.UseStock = true;
                w100.UseUnderline = true;
                w100.CanFocus = true;
                w100.Events = ((Gdk.EventMask)(0));
                w100.Name = "button1";
                w100.Label = "gtk-ok";
                bindings["button1"] = w100;
                w99.Add(w100);
                Gtk.ButtonBox.ButtonBoxChild w101 = ((Gtk.ButtonBox.ButtonBoxChild)(w99[w100]));
                w101.Expand = false;
                w101.Fill = false;
                bindings["hbuttonbox2"] = w99;
                w82.Add(w99);
                Gtk.Box.BoxChild w102 = ((Gtk.Box.BoxChild)(w82[w99]));
                w102.Position = 1;
                w102.Expand = false;
                w102.Fill = false;
                // Container child vbox2.Gtk.Box+BoxChild
                Gtk.Image w103 = new Gtk.Image();
                w103.Pixbuf = Gdk.Pixbuf.LoadFromResource("bottom.bmp");
                w103.Events = ((Gdk.EventMask)(0));
                w103.Name = "image3";
                bindings["image3"] = w103;
                w82.Add(w103);
                Gtk.Box.BoxChild w104 = ((Gtk.Box.BoxChild)(w82[w103]));
                w104.Position = 2;
                w104.Expand = false;
                w104.Fill = false;
                bindings["vbox2"] = w82;
                w3.Add(w82);
                Gtk.Box.BoxChild w105 = ((Gtk.Box.BoxChild)(w3[w82]));
                w105.Position = 2;
                w105.Expand = false;
                w105.Fill = false;
                bindings["vbox1"] = w3;
                cobj.Add(w3);
                cobj.DefaultHeight = 490;
                bindings["MainWindow"] = cobj;
                w5.Show();
                w8.Show();
                w10.Show();
                w12.Show();
                w7.Show();
                w16.Show();
                w19.Show();
                w21.Show();
                w23.Show();
                w18.Show();
                w28.Show();
                w27.Show();
                w32.Show();
                w34.Show();
                w31.Show();
                w38.Show();
                w40.Show();
                w37.Show();
                w26.Show();
                w15.Show();
                w4.Show();
                w48.Show();
                w50.Show();
                w47.Show();
                w56.Show();
                w55.Show();
                w59.Show();
                w54.Show();
                w53.Show();
                w65.Show();
                w67.Show();
                w71.Show();
                w73.Show();
                w75.Show();
                w70.Show();
                w69.Show();
                w64.Show();
                w63.Show();
                w46.Show();
                w85.Show();
                w84.Show();
                w89.Show();
                w91.Show();
                w93.Show();
                w88.Show();
                w96.Show();
                w83.Show();
                w100.Show();
                w99.Show();
                w103.Show();
                w82.Show();
                w3.Show();
                cobj.Show();
                cobj.DeleteEvent += ((Gtk.DeleteEventHandler)(System.Delegate.CreateDelegate(typeof(Gtk.DeleteEventHandler), cobj, "OnDeleteEvent")));
                w12.Clicked += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnButton10Clicked")));
                w23.Clicked += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnButton3Clicked")));
                w75.Clicked += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnButton12Clicked")));
                w100.Clicked += ((System.EventHandler)(System.Delegate.CreateDelegate(typeof(System.EventHandler), cobj, "OnButton1Clicked")));
            }
            System.Reflection.FieldInfo[] fields = obj.GetType().GetFields(((System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic) | System.Reflection.BindingFlags.Instance));
            for (int n = 0; (n < fields.Length); n = (n + 1)) {
                System.Reflection.FieldInfo field = fields[n];
                object widget = bindings[field.Name];
                if (((widget != null) && field.FieldType.IsInstanceOfType(widget))) {
                    field.SetValue(obj, widget);
                }
            }
        }
    }
    
    internal class ActionGroups {
        
        public static Gtk.ActionGroup GetActionGroup(System.Type type) {
            return Stetic.ActionGroups.GetActionGroup(type.FullName);
        }
        
        public static Gtk.ActionGroup GetActionGroup(string name) {
            return null;
        }
    }
}
